admin_person:
    path:     /
    defaults: { _controller: "OphFamilytreeBundle:Person:index" }

admin_person_show:
    path:     /{id}/show
    defaults: { _controller: "OphFamilytreeBundle:Person:show" }

admin_person_new:
    path:     /new
    defaults: { _controller: "OphFamilytreeBundle:Person:new" }

admin_person_create:
    path:     /create
    defaults: { _controller: "OphFamilytreeBundle:Person:create" }
    methods:  POST

admin_person_edit:
    path:     /{id}/edit
    defaults: { _controller: "OphFamilytreeBundle:Person:edit" }

admin_person_update:
    path:     /{id}/update
    defaults: { _controller: "OphFamilytreeBundle:Person:update" }
    methods:  [POST, PUT]

admin_person_delete:
    path:     /{id}/delete
    defaults: { _controller: "OphFamilytreeBundle:Person:delete" }
    methods:  [POST, DELETE]
