admin_image:
    path:     /
    defaults: { _controller: "OphFamilytreeBundle:Image:index" }

admin_image_show:
    path:     /{id}/show
    defaults: { _controller: "OphFamilytreeBundle:Image:show" }

admin_image_new:
    path:     /new
    defaults: { _controller: "OphFamilytreeBundle:Image:new" }

admin_image_create:
    path:     /create
    defaults: { _controller: "OphFamilytreeBundle:Image:create" }
    methods:  POST

admin_image_edit:
    path:     /{id}/edit
    defaults: { _controller: "OphFamilytreeBundle:Image:edit" }

admin_image_update:
    path:     /{id}/update
    defaults: { _controller: "OphFamilytreeBundle:Image:update" }
    methods:  [POST, PUT]

admin_image_delete:
    path:     /{id}/delete
    defaults: { _controller: "OphFamilytreeBundle:Image:delete" }
    methods:  [POST, DELETE]
