oph_familytree_homepage:
    path:     /
    defaults: { _controller: OphFamilytreeBundle:Leaf:index }
    
oph_familytree_tree:
    path:     /tree
    defaults: { _controller: OphFamilytreeBundle:Leaf:tree }

oph_familytree_map:
    path:     /map
    defaults: { _controller: OphFamilytreeBundle:Leaf:map }

oph_familytree_add:
    path:     /add
    defaults: { _controller: OphFamilytreeBundle:Leaf:add }

oph_familytree_edit:
    path:     /personne/{id}/edit
    defaults: { _controller: OphFamilytreeBundle:Leaf:edit }
    requirements:
        id: \d+

oph_familytree_edit_photos:
    path:     /personne/{id}/galerie/edit
    defaults: { _controller: OphFamilytreeBundle:Leaf:editPhotos }
    requirements:
        id: \d+

oph_familytree_edit_documents:
    path:     /personne/{id}/documents/editer
    defaults: { _controller: OphFamilytreeBundle:Leaf:editDocuments }
    requirements:
        id: \d+

oph_familytree_edit_one_document:
    path:     /personne/{id}/documents/editer/{idDocument}
    defaults: { _controller: OphFamilytreeBundle:Leaf:editOneDocument }
    requirements:
        id: \d+
        idDocument: \d+

oph_familytree_delete:
    path:     /personne/{id}/supprimer
    defaults: { _controller: OphFamilytreeBundle:Leaf:delete }
    requirements:
        id: \d+

oph_familytree_delete_avatar:
    path:     /personne/{id}/avatar/delete
    defaults: { _controller: OphFamilytreeBundle:Leaf:deleteAvatar }
    requirements:
        id: \d+

oph_familytree_delete_document:
    path:     /personne/{id}/documents/delete/{idDocument}
    defaults: { _controller: OphFamilytreeBundle:Leaf:deleteDocument }
    requirements:
        id: \d+
        idDocument: \d+

oph_familytree_delete_photo:
    path:     /personne/{id}/galerie/delete/{idPicture}
    defaults: { _controller: OphFamilytreeBundle:Leaf:deletePhoto }
    requirements:
        id: \d+
        idPicture: \d+

oph_familytree_view:
    path:     /personne/{id}
    defaults: { _controller: OphFamilytreeBundle:Leaf:view }
    requirements:
        id: \d+
