services:
#    oph_familytree.example:
#        class: Oph\FamilytreeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


services:
    oph_familytree.personservice:
        class: Oph\FamilytreeBundle\Service\PersonService
        calls:
         - [setEntityManager, ["@doctrine.orm.entity_manager"]]